import Head from "next/head"
import SideBar from "../components/SiderBar"
import Center from "../components/Center"
import { getSession } from "next-auth/react"
import Player from "../components/Player"

export default function Home() {
  return (
    <div className="flex-1">
      <Head>
        <title>Spotify 2.0 👊</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-black text-white flex ">
        <Center />
        <div className="fixed bottom-0 left-0 right-0 ">
          <Player />
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  return {
    props: {
      session,
    },
  }
}
