import { getSession } from "next-auth/react"
import Head from "next/head"
import Center from "../components/Center"

export default function Home() {
  return (
    <div className="flex-1">
      <Head>
        <title>Spotify 2.0 👊</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-black text-white flex ">
        <Center />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  return {
    props: {
      session,
    },
  }
}
